FROM node:18-alpine3.15 as build

RUN mkdir /app
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install 
RUN npm install -g @angular/cli@14.0.2

COPY . /app

RUN ng build --output-path=dist

FROM nginx:1.23.1-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]